spring:
  datasource:
    url: jdbc:mysql://localhost/superDB?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
