spring:

  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  batch:
    initialize-schema: ALWAYS