spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:bdacl
    initialization-mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create