spring:

  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
        exclude: ''
      base-path: /info
  endpoint:
    env:
      enabled: true
    configprops:
      enabled: true
    liquibase:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
    logfile:
      enabled: true

logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
  file: 'logs/log.log'